name: Build & Push Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checka ut koden
        uses: actions/checkout@v4

      - name: Installera Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Installera beroenden
        run: npm install

      - name: Bygg projektet
        run: npm run build

      - name: Pusha dist till release-bransch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: release
