name: Deploy till Inleed

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checka ut koden
        uses: actions/checkout@v4

      - name: Installera Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Installera beroenden
        run: npm install

      - name: Bygg projektet
        run: npm run build

      - name: Ladda upp filer via SSH/Rsync
        uses: easingthemes/ssh-deploy@v5.0.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.BM_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.BM_SSH_HOST }}
          REMOTE_USER: ${{ secrets.BM_SSH_USER }}
          PORT: 2020
          TARGET: "/home/bronsmedia/domains/bronsmedia.se/public_html/kampanj/releases/${{ github.event.repository.name }}/${{ github.sha }}"
          SOURCE: "dist/"
          ARGS: "-rltgoDz --delete"

      - name: Uppdatera Symlänk på Inleed
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BM_SSH_HOST }}
          username: ${{ secrets.BM_SSH_USER }}
          key: ${{ secrets.BM_SSH_PRIVATE_KEY }}
          script: |
            ln -sfn /home/bronsmedia/domains/bronsmedia.se/public_html/kampanj/releases/${{ github.event.repository.name }}/${{ github.sha }} /home/bronsmedia/domains/bronsmedia.se/public_html/kampanj/${{ github.event.repository.name }}
